### ISSUE TITLE
`./prm run` causes python error

### ISSUE THREAD

**Issue by anuramat** [aleksha/prm#3]
```
Traceback (most recent call last):
  File "merge_all.py", line 39, in <module>
    merge_two_files( f1="init/out.data", f2="scat/out.data", fm="temp1.data");
  File "merge_all.py", line 26, in merge_two_files
    f_merg.write( l_scat ) # write prev line
```
should be an easy fix, will do after making sure environment works properly

**Comment by aleksha** [comment]
I made some fixed already, but mabe not for all merge-scripts
