### ISSUE TITLE
`./prm setup-pilot` causes some errors

### ISSUE THREAD

**Issue by anuramat** [aleksha/prm#4]
<pre>
./prm setup-pilot

Setup AMBER-pilot geometry
'../code/g4app/pilot' -> 'source'
'../code/g4app/pilot/CMakeLists.txt' -> 'source/CMakeLists.txt'
'../code/g4app/pilot/GNUmakefile' -> 'source/GNUmakefile'
'../code/g4app/pilot/PRM.cc' -> 'source/PRM.cc'
'../code/g4app/pilot/README.md' -> 'source/README.md'
'../code/g4app/pilot/include' -> 'source/include'
'../code/g4app/pilot/include/PRMActionInitialization.hh' -> 'source/include/PRMActionInitialization.hh'
'../code/g4app/pilot/include/PRMDetectorConstruction.hh' -> 'source/include/PRMDetectorConstruction.hh'
'../code/g4app/pilot/include/PRMEventAction.hh' -> 'source/include/PRMEventAction.hh'
'../code/g4app/pilot/include/PRMPrimaryGeneratorAction.hh' -> 'source/include/PRMPrimaryGeneratorAction.hh'
'../code/g4app/pilot/include/PRMRunAction.hh' -> 'source/include/PRMRunAction.hh'
'../code/g4app/pilot/include/PRMSteppingAction.hh' -> 'source/include/PRMSteppingAction.hh'
'../code/g4app/pilot/include/chn.sh' -> 'source/include/chn.sh'
'../code/g4app/pilot/src' -> 'source/src'
'../code/g4app/pilot/src/PRMActionInitialization.cc' -> 'source/src/PRMActionInitialization.cc'
'../code/g4app/pilot/src/PRMDetectorConstruction.cc' -> 'source/src/PRMDetectorConstruction.cc'
'../code/g4app/pilot/src/PRMEventAction.cc' -> 'source/src/PRMEventAction.cc'
'../code/g4app/pilot/src/PRMPrimaryGeneratorAction.cc' -> 'source/src/PRMPrimaryGeneratorAction.cc'
'../code/g4app/pilot/src/PRMRunAction.cc' -> 'source/src/PRMRunAction.cc'
'../code/g4app/pilot/src/PRMSteppingAction.cc' -> 'source/src/PRMSteppingAction.cc'
'../code/g4app/pilot/src/chn.sh' -> 'source/src/chn.sh'
'../../configs/geom/amber-pilot/geom_config.h' -> './geom_config.h'
Make output/ directory
'../../code/setup/setup_mac.py' -> './setup_mac.py'
'../../configs/seeds/seed_init' -> 'seed'
'../../code/setup/setup_mac.py' -> './setup_mac.py'
'../../configs/seeds/seed_scat' -> 'seed'
'../../code/setup/setup_mac.py' -> './setup_mac.py'
'setup_mac.py' -> '../scripts_done/setup_mac.py'
'../../configs/seeds/seed_prot' -> 'seed'
# ostap                          INFO    Welcome to Ostap

                                        1.5.0.4 (Aug 28, 2020, 13:16 [UTC])
     .oooooo.                .
    d8P'  `Y8b             .o8
   888      888  .oooo.o .o888oo  .oooo.   oo.ooooo.
   888      888 d88(  "8   888   `P  )88b   888' `88b
   888      888 `"Y88b.    888    .oP"888   888   888
   `88b    d88' o.  )88b   888 . d8(  888   888   888
    `Y8bood8P'  8""888P'   "888" `Y888""8o  888bod8P'
                                            888
                                           o888o

 - https://github.com/OstapHEP/ostap
 - https://ostaphep.github.io/ostap-tutorials
 - https://github.com/OstapHEP/ostap-tutorials

# ostap                          INFO     Simple interactive PyRoot-based analysis environment
to provide access to zillions useful decorators for ROOT
(and not only ROOT) objects&classes

# ostap                          INFO    Arguments  :
# ostap                          INFO                Color : True
# ostap                          INFO             Commands : []
# ostap                          INFO               Config : []
# ostap                          INFO               Macros : []
# ostap                          INFO         NoImplicitMT : False
# ostap                          INFO              Profile : False
# ostap                          INFO                Quiet : False
# ostap                          INFO              Verbose : False
# ostap                          INFO          WithContext : True
# ostap                          INFO                batch : True
# ostap                          INFO            build_dir :
# ostap                          INFO               canvas : True
# ostap                          INFO                embed : False
# ostap                          INFO                files : ['create.py']
# ostap                          INFO               simple : False
# ostap                          INFO    Batch processing is activated
# ostap.core.startup             INFO    Ostap  session started Wed Apr 21 19:45:18 2021
# ostap.core.pyrouts             INFO    Zillions of decorations for ROOT/RooFit objects
TFile**		../external/beam/beamfile_prm_mu100.root
 TFile*		../external/beam/beamfile_prm_mu100.root
  KEY: TTree	BeamFile;2	BeamFile
  KEY: TTree	BeamFile;1	BeamFile
<b>
Error in <TFile::TFile>: file ../external/esepp/"events"_mu-.root does not exist
Traceback (most recent call last):
  File "/home/admin/miniconda3/envs/prm-env/bin/ostap", line 38, in <module>
    from ostap.core.run_ostap import *
  File "/home/admin/miniconda3/envs/prm-env/lib/python3.8/site-packages/ROOT.py", line 522, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/home/admin/miniconda3/envs/prm-env/lib/python3.8/site-packages/ostap/core/run_ostap.py", line 586, in <module>
    treat_file ( _f      )
  File "/home/admin/miniconda3/envs/prm-env/lib/python3.8/site-packages/ostap/core/run_ostap.py", line 503, in treat_file
    globs = runpy.run_path (
  File "/home/admin/miniconda3/envs/prm-env/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/admin/miniconda3/envs/prm-env/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/admin/miniconda3/envs/prm-env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "create.py", line 10, in <module>
    efile = ROOT.TFile("../external/esepp/\"events\"_mu-.root", "READ")
  File "/home/admin/miniconda3/envs/prm-env/lib/python3.8/site-packages/ostap/io/root_file.py", line 853, in _rf_new_init_
    raise IOError   ( "Can't open ROOT file %s/'%s'" % ( fname , mode ) )
OSError: Can't open ROOT file ../external/esepp/"events"_mu-.root/'READ'
</b>
# ostap.core.startup             INFO    Ostap  session   ended Wed Apr 21 19:45:28 2021 [9.7s]
# ostap.core.config              INFO    Ostap  configuration saved: .ostap_config.txt
<b>
mv: cannot stat 'init_lepton.txt': No such file or directory
mv: cannot stat 'scat_lepton.txt': No such file or directory
mv: cannot stat 'scat_proton.txt': No such file or directory
</b>
# ostap                          INFO    Welcome to Ostap

                                        1.5.0.4 (Aug 28, 2020, 13:16 [UTC])
     .oooooo.                .
    d8P'  `Y8b             .o8
   888      888  .oooo.o .o888oo  .oooo.   oo.ooooo.
   888      888 d88(  "8   888   `P  )88b   888' `88b
   888      888 `"Y88b.    888    .oP"888   888   888
   `88b    d88' o.  )88b   888 . d8(  888   888   888
    `Y8bood8P'  8""888P'   "888" `Y888""8o  888bod8P'
                                            888
                                           o888o

 - https://github.com/OstapHEP/ostap
 - https://ostaphep.github.io/ostap-tutorials
 - https://github.com/OstapHEP/ostap-tutorials

# ostap                          INFO     Simple interactive PyRoot-based analysis environment
to provide access to zillions useful decorators for ROOT
(and not only ROOT) objects&classes

# ostap                          INFO    Arguments  :
# ostap                          INFO                Color : True
# ostap                          INFO             Commands : []
# ostap                          INFO               Config : []
# ostap                          INFO               Macros : []
# ostap                          INFO         NoImplicitMT : False
# ostap                          INFO              Profile : False
# ostap                          INFO                Quiet : False
# ostap                          INFO              Verbose : False
# ostap                          INFO          WithContext : True
# ostap                          INFO                batch : True
# ostap                          INFO            build_dir :
# ostap                          INFO               canvas : True
# ostap                          INFO                embed : False
# ostap                          INFO                files : ['create_beam.py']
# ostap                          INFO               simple : False
# ostap                          INFO    Batch processing is activated
# ostap.core.startup             INFO    Ostap  session started Wed Apr 21 19:45:29 2021
# ostap.core.pyrouts             INFO    Zillions of decorations for ROOT/RooFit objects
TFile**		../external/beam/beamfile_prm_mu100.root
 TFile*		../external/beam/beamfile_prm_mu100.root
  KEY: TTree	BeamFile;2	BeamFile
  KEY: TTree	BeamFile;1	BeamFile
<b>
Error in <TFile::TFile>: file ../external/esepp/"events"_mu-.root does not exist
Traceback (most recent call last):
  File "/home/admin/miniconda3/envs/prm-env/bin/ostap", line 38, in <module>
    from ostap.core.run_ostap import *
  File "/home/admin/miniconda3/envs/prm-env/lib/python3.8/site-packages/ROOT.py", line 522, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/home/admin/miniconda3/envs/prm-env/lib/python3.8/site-packages/ostap/core/run_ostap.py", line 586, in <module>
    treat_file ( _f      )
  File "/home/admin/miniconda3/envs/prm-env/lib/python3.8/site-packages/ostap/core/run_ostap.py", line 503, in treat_file
    globs = runpy.run_path (
  File "/home/admin/miniconda3/envs/prm-env/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/admin/miniconda3/envs/prm-env/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/admin/miniconda3/envs/prm-env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "create_beam.py", line 10, in <module>
    efile = ROOT.TFile("../external/esepp/\"events\"_mu-.root", "READ")
  File "/home/admin/miniconda3/envs/prm-env/lib/python3.8/site-packages/ostap/io/root_file.py", line 853, in _rf_new_init_
    raise IOError   ( "Can't open ROOT file %s/'%s'" % ( fname , mode ) )
OSError: Can't open ROOT file ../external/esepp/"events"_mu-.root/'READ'
</b>
# ostap.core.startup             INFO    Ostap  session   ended Wed Apr 21 19:45:36 2021 [7.0s]
# ostap.core.config              INFO    Ostap  configuration saved: .ostap_config.txt
<b>
mv: cannot stat 'run.mac': No such file or directory
mv: cannot stat 'rand_beam.txt': No such file or directory
control/setup_pilot.sh: line 47: O: команда не найдена
</b>
Setup is done. You can try to build app.

Don't forget:
   conda activate g4-mc

</pre>

**Comment by aleksha** [comment]
Here one have to generate esepp file prior to setup
